name: Build macOS Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build the application with PyInstaller
      run: pyinstaller --name "Transcript Filter" --windowed --noconfirm main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # <-- ИСПРАВЛЕННАЯ СТРОКА
      with:
        name: Transcript-Filter-macOS
        path: dist/Transcript Filter.app
